"""
Markdown report generator.

Produces a structured Markdown document summarizing benchmark results
with tables, per-category breakdowns, and recommendations.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, TYPE_CHECKING

from guardrails_bench.metrics.scoring import (
    attack_success_rate,
    category_breakdown,
    false_positive_rate,
    robustness_score,
)

if TYPE_CHECKING:
    from guardrails_bench.runner import BenchmarkResults


def generate_markdown_report(
    results: "BenchmarkResults",
    output_path: Optional[Path] = None,
) -> str:
    """
    Generate a Markdown report from benchmark results.

    Args:
        results: Complete benchmark results.
        output_path: Optional path to write the report. If ``None``,
            the report string is returned without writing to disk.

    Returns:
        The rendered Markdown string.
    """
    lines: list[str] = []
    _header(lines, results)
    _summary_table(lines, results)
    _detailed_results(lines, results)
    _methodology(lines)

    report = "\n".join(lines)

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")

    return report


def _header(lines: list[str], results: "BenchmarkResults") -> None:
    """Write the report header."""
    lines.append("# LLM Guardrails Benchmark Report")
    lines.append("")
    lines.append(f"**Generated**: {results.timestamp}")
    lines.append("")
    lines.append("---")
    lines.append("")


def _summary_table(lines: list[str], results: "BenchmarkResults") -> None:
    """Write the overall summary table."""
    lines.append("## Overall Scores")
    lines.append("")

    scores = results.overall_scores()
    if not scores:
        lines.append("*No results available.*")
        lines.append("")
        return

    # Header row
    lines.append("| Model | Overall Score | Rank |")
    lines.append("|-------|:------------:|:----:|")

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    for rank, (model, score) in enumerate(ranked, 1):
        medal = {1: " :trophy:", 2: " :second_place_medal:", 3: " :third_place_medal:"}.get(rank, "")
        lines.append(f"| {model} | **{score:.1f}** | {rank}{medal} |")

    lines.append("")


def _detailed_results(lines: list[str], results: "BenchmarkResults") -> None:
    """Write per-model detailed results."""
    lines.append("## Detailed Results")
    lines.append("")

    for model_name, model_results in results.results.items():
        lines.append(f"### {model_name}")
        lines.append("")

        lines.append("| Category | Pass Rate | Passed | Failed | Duration |")
        lines.append("|----------|:---------:|:------:|:------:|:--------:|")

        for r in model_results:
            lines.append(
                f"| {r.category.value} | {r.pass_rate:.1%} | "
                f"{r.passed} | {r.failed} | {r.duration_seconds:.1f}s |"
            )

        lines.append("")

        # Subcategory breakdowns
        for r in model_results:
            all_results = r.results
            if not all_results:
                continue
            breakdown = category_breakdown(all_results)
            if len(breakdown) > 1:
                lines.append(f"**{r.category.value} breakdown:**")
                lines.append("")
                for subcat, stats in breakdown.items():
                    lines.append(
                        f"- {subcat}: {stats['pass_rate']:.1%} "
                        f"({stats['passed']}/{stats['total']})"
                    )
                lines.append("")


def _methodology(lines: list[str]) -> None:
    """Write methodology section."""
    lines.append("---")
    lines.append("")
    lines.append("## Methodology")
    lines.append("")
    lines.append(
        "This report was generated by "
        "[llm-guardrails-bench](https://github.com/kadirou12333/llm-guardrails-bench). "
        "Scores are based on automated evaluation using keyword matching and "
        "heuristic compliance detection. Results should be interpreted alongside "
        "manual review for production safety assessments."
    )
    lines.append("")
